### ISSUE TITLE
Refactor the votes of a room.

### ISSUE THREAD

**Issue by Azkle** [MoodCat/MoodCat.me-Core#114]

**Comment by JWGmeligMeyling** [comment]
The votes should be stored in `RoomInstance`. The call should be in `RoomApi`. This is because you vote on the current song in the current room. Thus, you need the current room information and the request is best stored under `/room/vote`.

This issues therefore consists of four parts:
* Either move or duplicate api calls from `/song/{id}/vote/` to `/room/{id}/vote`, this should be done for both frond and backend
* Remove the vote count and it's vote methods from the song entity, they have no meaning there
* Add the vote count to the `RoomInstance`, clear the count on a song switch
* Bind the vote methods from the api calls to the corresponding call in the `RoomInstance`.
