### ISSUE TITLE
Update the database

### ISSUE THREAD

**Issue by Azkle** [MoodCat/MoodCat.me-Core#115]

**Comment by JeremybellEU** [comment]
Could you @jaapp- please explain what you did and what has been fixed?

**Comment by Jaapp-** [comment]
Yes.
Rooms now have a play queue and a play history.
In table room: song has been renamed to currentsong because it's not the room's only song anymore.
The column 'position' has been removed and a new column of type boolean named 'repeat' has been added, if repeat is true, the room will repeat its queue when finished.
There are two new tables: room_play_history and room_play_queue, they both have the same schema: a room_id and song_id, both are many to many relations to the tables room and song.
