### ISSUE TITLE
Set up Lombok

### ISSUE THREAD

**Issue by JeremybellEU** [MoodCat/MoodCat.me-Core#21]
Set up Lombok to easier create getters, setters and to deter general code clutter.

**Comment by JWGmeligMeyling** [comment]
Ah really would love to see Lombok being used. Another nice thing is that equals/hashcode generation can be really error prone, especially when objects change over time and all of a sudden set/map operations fail. Lombok does it for you.

However, because of the non-trivial way lombok works and the required installation to get things work inside the IDE we might want to verify if the TA is OK with it.
