### ISSUE TITLE
Remove songs in a room history from suggestion

### ISSUE THREAD

**Issue by TimvdLippe** [MoodCat/MoodCat.me-Core#77]
To deter users listening to the same song all over again, the song-selection algorithm should remove all songs that are in the room history. See #76.

**Comment by JWGmeligMeyling** [comment]
This problem was mostly related to the fact that I accidentally changed the fetch query from 25 results to 5 results to make it respond quicker to newly classified songs. This however caused songs to repeat very often, because the query would just return the same results every time. This was then fixed quickly afterwards (https://github.com/MoodCat/MoodCat.me-Core/commit/c0bf4ca29602347f0f2379cb7d2af435da8702c1). I think we should instead improve on the randomness of our algorithm, and use the room exclusions / vote downs as a mechanism to correct wrong suggestions.

**Comment by JWGmeligMeyling** [comment]
Also keep in mind that there are only 100 songs classified over about 10 moods. There simply isnt so much choice yet.
